services:
  o6kr7a9xvb:
    container_name: o6kr7a9xvb_app
    image: ghcr.io/mr-devloper005/empoweryouroad.com:latest
    env_file:
      - .env
    network_mode: bridge
    restart: always
    ports:
      - "127.0.0.1:3267:3000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:3000/"]
      interval: 5m
      timeout: 3s
      retries: 2
